# Generated by Django 3.2.5 on 2021-07-06 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='seat_db',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('left_win', models.IntegerField()),
                ('center', models.IntegerField()),
                ('right_win', models.IntegerField()),
            ],
        ),
    ]
