# Generated by Django 3.2.5 on 2021-07-06 16:43

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ticket_api_app', '0002_bocked_db'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='bocked_db',
            new_name='booked_db',
        ),
    ]
