# Generated by Django 3.2.5 on 2021-07-09 05:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ticket_api_app', '0003_rename_bocked_db_booked_db'),
    ]

    operations = [
        migrations.DeleteModel(
            name='booked_db',
        ),
    ]
