# Generated by Django 3.2.5 on 2021-07-09 05:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ticket_api_app', '0004_delete_booked_db'),
    ]

    operations = [
        migrations.CreateModel(
            name='booked_db',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.DateTimeField(auto_now_add=True)),
                ('f_name', models.CharField(max_length=100)),
                ('seat_type', models.IntegerField()),
                ('seat_no', models.IntegerField()),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
