# Generated by Django 3.2.5 on 2021-07-09 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticket_api_app', '0005_booked_db'),
    ]

    operations = [
        migrations.CreateModel(
            name='seat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('status', models.CharField(default='AVALIBLE', max_length=100)),
            ],
        ),
    ]
