# Generated by Django 3.2.5 on 2021-07-09 13:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ticket_api_app', '0006_seat'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='seat',
            new_name='seat_new',
        ),
    ]
