# Generated by Django 3.2.5 on 2021-07-09 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticket_api_app', '0008_auto_20210709_2127'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booked_db',
            name='seat_no',
            field=models.CharField(max_length=100),
        ),
    ]
