# Generated by Django 3.2.5 on 2021-07-10 10:51

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ticket_api_app', '0009_alter_booked_db_seat_no'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='booked_db',
            new_name='booking_db',
        ),
        migrations.RenameModel(
            old_name='seat_new',
            new_name='flight_one_db',
        ),
        migrations.DeleteModel(
            name='seat_db',
        ),
        migrations.RenameField(
            model_name='flight_one_db',
            old_name='name',
            new_name='seat_name',
        ),
    ]
