# Generated by Django 3.2.5 on 2021-07-11 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticket_api_app', '0011_auto_20210711_2201'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking_db',
            name='booking_name',
            field=models.CharField(default='--NA--', max_length=100),
        ),
        migrations.AlterField(
            model_name='flight_one_db',
            name='booking_id',
            field=models.CharField(default='--NA--', max_length=100),
        ),
    ]
