# Generated by Django 3.2.5 on 2021-07-11 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticket_api_app', '0013_remove_booking_db_booking_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking_db',
            name='booking_name',
            field=models.CharField(default='--NA--', max_length=100),
        ),
    ]
