# Generated by Django 3.0.6 on 2021-07-14 16:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ticket_api_app', '0016_booking_db_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking_db',
            name='slug',
        ),
    ]
