# Generated by Django 3.0.6 on 2021-07-19 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticket_api_app', '0021_auto_20210715_1644'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flight_one_db',
            name='status',
            field=models.CharField(default='AVAILABLE', max_length=100),
        ),
        migrations.AlterField(
            model_name='flight_two_db',
            name='status',
            field=models.CharField(default='AVAILABLE', max_length=100),
        ),
    ]
