# Generated by Django 3.0.6 on 2021-07-22 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticket_api_app', '0022_auto_20210719_1806'),
    ]

    operations = [
        migrations.CreateModel(
            name='flight_db',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('f_name', models.CharField(max_length=100)),
                ('s_n_d', models.CharField(max_length=100)),
                ('ava_seat', models.IntegerField(max_length=800)),
            ],
        ),
    ]
