# Generated by Django 3.0.6 on 2021-08-04 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticket_api_app', '0023_flight_db'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flight_db',
            name='ava_seat',
            field=models.IntegerField(default=30),
        ),
    ]
